/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    properties: Property;
    'project-units': ProjectUnit;
    projects: Project;
    companies: Company;
    areas: Area;
    articles: Article;
    'listing-requests': ListingRequest;
    enquiries: Enquiry;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'project-units': ProjectUnitsSelect<false> | ProjectUnitsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'listing-requests': ListingRequestsSelect<false> | ListingRequestsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sq' | 'en' | 'it') | ('sq' | 'en' | 'it')[];
  globals: {};
  globalsSelect: {};
  locale: 'sq' | 'en' | 'it';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Prona individuale. Njësitë e projekteve janë koleksion më vete.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  /**
   * Për truall fshihen dhomat, kati dhe orientimi.
   */
  propertyType: 'apartment' | 'villa' | 'house' | 'shop' | 'office' | 'warehouse' | 'land';
  listingType: 'sale' | 'rent';
  /**
   * Gjendja te blerësi. Nuk ka lidhje me publikimin: një pronë e rezervuar mbetet e publikuar në sajt.
   */
  status: 'available' | 'reserved' | 'sold';
  /**
   * Niveli i përfundimit të kësaj ndërtese. Ndryshe nga faza e një projekti të ri.
   */
  buildingPhase?: ('brick' | 'facade' | 'finished' | 'existing') | null;
  /**
   * Prona pranohet për kredi bankare. Filtër kryesor në këtë treg — mos e lër bosh nëse e di përgjigjen.
   */
  mortgageEligible?: boolean | null;
  /**
   * Lagjja ose qyteti. Kjo është ajo mbi të cilën filtrohet kërkimi.
   */
  area: number | Area;
  street?: string | null;
  /**
   * P.sh. “Pranë Rotondës”.
   */
  landmark?: string | null;
  /**
   * Lëvize shënjuesin mbi ndërtesë. Ushqen hartën dhe kërkimin me rreze.
   *
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  /**
   * Zgjidhe kur pronari nuk do çmim publik. Fusha e çmimit fshihet dhe prona shfaqet si “Çmimi me kërkesë”.
   */
  priceOnRequest?: boolean | null;
  price?: number | null;
  /**
   * Shkruaje çmimin siç e jep pronari. Konvertimi bëhet vetë.
   */
  currency?: ('EUR' | 'ALL') | null;
  rentPeriod?: ('monthly' | 'nightly') | null;
  /**
   * Bruto: me muret dhe pjesën takuese, siç shitet. Çmimi për m² llogaritet mbi këtë fushë.
   */
  areaGross: number;
  /**
   * Vetëm sipërfaqja e brendshme e shfrytëzueshme. Gjithmonë më e vogël se bruto.
   */
  areaNet?: number | null;
  /**
   * Jashtë sipërfaqes neto.
   */
  terraceSqm?: number | null;
  /**
   * Pjesa takuese e shkallëve dhe korridoreve.
   */
  commonAreaSqm?: number | null;
  /**
   * Konventa shqiptare: 2+1, 1+1+2. Numri para “+” janë dhomat e gjumit, pas tij dhoma e ndenjes.
   */
  rooms?: string | null;
  /**
   * Vetëm numri, për filtrat.
   */
  bedrooms?: number | null;
  bathrooms?: number | null;
  /**
   * 0 = përdhesë. Nëntokë shkruhet me minus, p.sh. -1.
   */
  floor?: number | null;
  /**
   * Zgjidh të gjitha anët që ka prona, shpesh dy ose tre.
   */
  orientation?: ('N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW')[] | null;
  /**
   * Këto janë filtrat e kërkimit. Opsionet shtohen në kod — mos shkruaj tekst të lirë.
   */
  features?:
    | (
        | 'parking'
        | 'elevator'
        | 'balcony'
        | 'terrace'
        | 'garden'
        | 'pool'
        | 'furnished'
        | 'seaView'
        | 'cityView'
        | 'lakeView'
        | 'heating'
        | 'airConditioning'
        | 'security'
        | 'storage'
        | 'streetFront'
      )[]
    | null;
  /**
   * Foto e parë është ajo që shfaqet në listë. Të paktën një foto është e detyrueshme.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shkruaje pasi ke plotësuar të dhënat. P.sh. “Apartament 2+1 te Bllok, 96 m²”.
   */
  title: string;
  /**
   * Gjendja, pozicioni, ç’ka afër. Pa numra telefoni dhe pa çmim.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Publike. Çfarë dokumentacioni ka verifikuar Atmos për këtë pronë.
   */
  documentationNote?: string | null;
  ownerName?: string | null;
  ownerPhone?: string | null;
  /**
   * Vetëm për ekipin. Nuk dalin as në API publike.
   */
  internalNotes?: string | null;
  /**
   * Krijohet vetë nga titulli shqip. Po e ndryshove, lidhjet ekzistuese prishen.
   */
  slug: string;
  /**
   * P.sh. ATM-2026-0142.
   */
  reference?: string | null;
  /**
   * Kjo pronë i përket këtij agjenti. Vetëm administratori mund ta ndryshojë.
   */
  agent: number | User;
  /**
   * I llogaritur. Vetëm për renditje dhe filtra.
   */
  priceEur?: number | null;
  /**
   * Vendoset vetë kur publikohet për herë të parë.
   */
  publishedAt?: string | null;
  verified?: boolean | null;
  featured?: boolean | null;
  /**
   * Kërkesa e pronarit nga e cila lindi kjo pronë.
   */
  sourceRequest?: (number | null) | ListingRequest;
  seo?: {
    /**
     * Lëre bosh që të krijohet vetë nga titulli.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nëse bosh, merret fotoja e parë e galerisë.
     */
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Qytete dhe lagje. Çdo pronë lidhet me një zonë.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  name: string;
  /**
   * Krijohet vetë nga titulli shqip. Po e ndryshove, lidhjet ekzistuese prishen.
   */
  slug: string;
  /**
   * Vetëm dy nivele: qytet, ose lagje brenda një qyteti.
   */
  kind: 'city' | 'neighbourhood';
  parent?: (number | null) | Area;
  /**
   * @minItems 2
   * @maxItems 2
   */
  center?: [number, number] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Lëre bosh që të krijohet vetë nga titulli.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nëse bosh, merret fotoja e parë e galerisë.
     */
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Përshkruaj çfarë duket në foto. E nevojshme për çdo foto që shfaqet te vizitorët.
   */
  alt?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Vetëm administratori mund ta ndryshojë rolin.
   */
  role: 'admin' | 'agent' | 'client';
  /**
   * Shfaqet publikisht te pronat e këtij agjenti dhe përdoret për WhatsApp. Me kod shteti, p.sh. +355 69 20 11 555.
   */
  phone?: string | null;
  photo?: (number | null) | Media;
  /**
   * Publik. Shfaqet te kartela e agjentit në faqen e pronës.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Prona që dërgojnë vetë pronarët. Verifikoji, pastaj krijo pronën me dorë.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-requests".
 */
export interface ListingRequest {
  id: number;
  requestStatus: 'new' | 'contacted' | 'verified' | 'published' | 'rejected';
  ownerName: string;
  ownerPhone: string;
  ownerEmail?: string | null;
  city: string;
  areaName?: string | null;
  address?: string | null;
  listingType: 'sale' | 'rent';
  /**
   * Siç e ka shkruar pronari, tekst i lirë.
   */
  propertyType?: string | null;
  rooms?: string | null;
  areaSqm?: number | null;
  floor?: number | null;
  askingPrice?: number | null;
  description?: string | null;
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  hasDocumentation?: boolean | null;
  termsVersion: string;
  termsAcceptedAt: string;
  submittedLocale?: string | null;
  /**
   * Hash i kriptuar, vetëm për kufizimin e abuzimeve.
   */
  ipHash?: string | null;
  assignedAgent?: (number | null) | User;
  internalNotes?: string | null;
  rejectionReason?: string | null;
  /**
   * Lidhe pasi prona të jetë publikuar.
   */
  linkedProperty?: (number | null) | Property;
  updatedAt: string;
  createdAt: string;
}
/**
 * Njësitë brenda një projekti. Zonën dhe vendndodhjen i marrin nga projekti.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-units".
 */
export interface ProjectUnit {
  id: number;
  /**
   * Zona, vendndodhja dhe investitori merren nga ky projekt.
   */
  project: number | Project;
  /**
   * P.sh. A-4-2 ose Ap. 12.
   */
  unitCode: string;
  building?: string | null;
  floorPlan?: (number | null) | Media;
  /**
   * Për truall fshihen dhomat, kati dhe orientimi.
   */
  propertyType: 'apartment' | 'villa' | 'house' | 'shop' | 'office' | 'warehouse' | 'land';
  listingType: 'sale' | 'rent';
  /**
   * Gjendja te blerësi. Nuk ka lidhje me publikimin: një pronë e rezervuar mbetet e publikuar në sajt.
   */
  status: 'available' | 'reserved' | 'sold';
  /**
   * Niveli i përfundimit të kësaj ndërtese. Ndryshe nga faza e një projekti të ri.
   */
  buildingPhase?: ('brick' | 'facade' | 'finished' | 'existing') | null;
  /**
   * Prona pranohet për kredi bankare. Filtër kryesor në këtë treg — mos e lër bosh nëse e di përgjigjen.
   */
  mortgageEligible?: boolean | null;
  /**
   * Zgjidhe kur pronari nuk do çmim publik. Fusha e çmimit fshihet dhe prona shfaqet si “Çmimi me kërkesë”.
   */
  priceOnRequest?: boolean | null;
  price?: number | null;
  /**
   * Shkruaje çmimin siç e jep pronari. Konvertimi bëhet vetë.
   */
  currency?: ('EUR' | 'ALL') | null;
  rentPeriod?: ('monthly' | 'nightly') | null;
  /**
   * Bruto: me muret dhe pjesën takuese, siç shitet. Çmimi për m² llogaritet mbi këtë fushë.
   */
  areaGross: number;
  /**
   * Vetëm sipërfaqja e brendshme e shfrytëzueshme. Gjithmonë më e vogël se bruto.
   */
  areaNet?: number | null;
  /**
   * Jashtë sipërfaqes neto.
   */
  terraceSqm?: number | null;
  /**
   * Pjesa takuese e shkallëve dhe korridoreve.
   */
  commonAreaSqm?: number | null;
  /**
   * Konventa shqiptare: 2+1, 1+1+2. Numri para “+” janë dhomat e gjumit, pas tij dhoma e ndenjes.
   */
  rooms?: string | null;
  /**
   * Vetëm numri, për filtrat.
   */
  bedrooms?: number | null;
  bathrooms?: number | null;
  /**
   * 0 = përdhesë. Nëntokë shkruhet me minus, p.sh. -1.
   */
  floor?: number | null;
  /**
   * Zgjidh të gjitha anët që ka prona, shpesh dy ose tre.
   */
  orientation?: ('N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW')[] | null;
  /**
   * Këto janë filtrat e kërkimit. Opsionet shtohen në kod — mos shkruaj tekst të lirë.
   */
  features?:
    | (
        | 'parking'
        | 'elevator'
        | 'balcony'
        | 'terrace'
        | 'garden'
        | 'pool'
        | 'furnished'
        | 'seaView'
        | 'cityView'
        | 'lakeView'
        | 'heating'
        | 'airConditioning'
        | 'security'
        | 'storage'
        | 'streetFront'
      )[]
    | null;
  /**
   * Foto e parë është ajo që shfaqet në listë. Të paktën një foto është e detyrueshme.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shkruaje pasi ke plotësuar të dhënat. P.sh. “Apartament 2+1 te Bllok, 96 m²”.
   */
  title: string;
  /**
   * Gjendja, pozicioni, ç’ka afër. Pa numra telefoni dhe pa çmim.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Krijohet vetë nga titulli shqip. Po e ndryshove, lidhjet ekzistuese prishen.
   */
  slug: string;
  /**
   * I llogaritur. Vetëm për renditje dhe filtra.
   */
  priceEur?: number | null;
  /**
   * Vendoset vetë kur publikohet për herë të parë.
   */
  publishedAt?: string | null;
  seo?: {
    /**
     * Lëre bosh që të krijohet vetë nga titulli.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nëse bosh, merret fotoja e parë e galerisë.
     */
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Rezidenca dhe komplekse të reja. Njësitë shtohen te “Njësitë”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * Krijohet vetë nga titulli shqip. Po e ndryshove, lidhjet ekzistuese prishen.
   */
  slug: string;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  developer: number | Company;
  area: number | Area;
  /**
   * Njësitë e këtij projekti e trashëgojnë këtë vendndodhje.
   *
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  /**
   * Merr kërkesat për këtë projekt dhe për të gjitha njësitë e tij.
   */
  agent?: (number | null) | User;
  /**
   * Faza e gjithë projektit. Ndryshe nga faza e një njësie të veçantë.
   */
  constructionPhase: 'planning' | 'underConstruction' | 'completed';
  completionDate?: string | null;
  /**
   * Fotoja e parë shfaqet në listën e projekteve.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  sitePlan?: (number | null) | Media;
  brochure?: (number | null) | Media;
  /**
   * E llogaritur nga njësitë e publikuara. Nuk plotësohet me dorë.
   */
  unitTypesSummary?:
    | {
        rooms?: string | null;
        areaFrom?: number | null;
        areaTo?: number | null;
        priceFrom?: number | null;
        availableCount?: number | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  seo?: {
    /**
     * Lëre bosh që të krijohet vetë nga titulli.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nëse bosh, merret fotoja e parë e galerisë.
     */
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Investitorë dhe kompani ndërtimi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  /**
   * Krijohet vetë nga titulli shqip. Po e ndryshove, lidhjet ekzistuese prishen.
   */
  slug: string;
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  foundedYear?: number | null;
  website?: string | null;
  phone?: string | null;
  email?: string | null;
  socials?:
    | {
        platform?: ('facebook' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  areasOfOperation?: (number | Area)[] | null;
  certifications?:
    | {
        title: string;
        issuer?: string | null;
        year?: number | null;
        document?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Vetëm administratori. Kjo ndez distinktivin e partnerit në sajt.
   */
  verifiedPartner?: boolean | null;
  legalName?: string | null;
  /**
   * Numri i identifikimit tatimor. I brendshëm.
   */
  nipt?: string | null;
  seo?: {
    /**
     * Lëre bosh që të krijohet vetë nga titulli.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nëse bosh, merret fotoja e parë e galerisë.
     */
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Krijohet vetë nga titulli shqip. Po e ndryshove, lidhjet ekzistuese prishen.
   */
  slug: string;
  /**
   * Dy fjali që shfaqen në listë dhe në Google.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  category: 'buying' | 'selling' | 'investment' | 'documentation' | 'market' | 'projects';
  relatedAreas?: (number | Area)[] | null;
  relatedCompanies?: (number | Company)[] | null;
  relatedProjects?: (number | Project)[] | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  /**
   * Përmbajtja e sponsorizuar shënohet si e tillë në faqe. Nuk është me zgjedhje.
   */
  contentType: 'editorial' | 'analysis' | 'sponsored';
  seo?: {
    /**
     * Lëre bosh që të krijohet vetë nga titulli.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nëse bosh, merret fotoja e parë e galerisë.
     */
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Kontakte nga faqet e pronave dhe projekteve. Kthe përgjigje brenda ditës.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  message?: string | null;
  sourceType: 'property' | 'unit' | 'project';
  sourceId: string;
  sourceTitle?: string | null;
  locale?: string | null;
  /**
   * Shënoje pasi ta kesh kontaktuar personin.
   */
  handled?: boolean | null;
  /**
   * Merret nga prona ose projekti kur dërgohet. Bosh do të thotë se shkoi te kutia e përbashkët.
   */
  assignedAgent?: (number | null) | User;
  termsVersion?: string | null;
  termsAcceptedAt?: string | null;
  /**
   * Hash i kriptuar, vetëm për kufizimin e abuzimeve.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'project-units';
        value: number | ProjectUnit;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'listing-requests';
        value: number | ListingRequest;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  propertyType?: T;
  listingType?: T;
  status?: T;
  buildingPhase?: T;
  mortgageEligible?: T;
  area?: T;
  street?: T;
  landmark?: T;
  location?: T;
  priceOnRequest?: T;
  price?: T;
  currency?: T;
  rentPeriod?: T;
  areaGross?: T;
  areaNet?: T;
  terraceSqm?: T;
  commonAreaSqm?: T;
  rooms?: T;
  bedrooms?: T;
  bathrooms?: T;
  floor?: T;
  orientation?: T;
  features?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  title?: T;
  description?: T;
  documentationNote?: T;
  ownerName?: T;
  ownerPhone?: T;
  internalNotes?: T;
  slug?: T;
  reference?: T;
  agent?: T;
  priceEur?: T;
  publishedAt?: T;
  verified?: T;
  featured?: T;
  sourceRequest?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-units_select".
 */
export interface ProjectUnitsSelect<T extends boolean = true> {
  project?: T;
  unitCode?: T;
  building?: T;
  floorPlan?: T;
  propertyType?: T;
  listingType?: T;
  status?: T;
  buildingPhase?: T;
  mortgageEligible?: T;
  priceOnRequest?: T;
  price?: T;
  currency?: T;
  rentPeriod?: T;
  areaGross?: T;
  areaNet?: T;
  terraceSqm?: T;
  commonAreaSqm?: T;
  rooms?: T;
  bedrooms?: T;
  bathrooms?: T;
  floor?: T;
  orientation?: T;
  features?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  title?: T;
  description?: T;
  slug?: T;
  priceEur?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  developer?: T;
  area?: T;
  location?: T;
  agent?: T;
  constructionPhase?: T;
  completionDate?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  sitePlan?: T;
  brochure?: T;
  unitTypesSummary?:
    | T
    | {
        rooms?: T;
        areaFrom?: T;
        areaTo?: T;
        priceFrom?: T;
        availableCount?: T;
        id?: T;
      };
  featured?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  about?: T;
  logo?: T;
  coverImage?: T;
  foundedYear?: T;
  website?: T;
  phone?: T;
  email?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  areasOfOperation?: T;
  certifications?:
    | T
    | {
        title?: T;
        issuer?: T;
        year?: T;
        document?: T;
        id?: T;
      };
  verifiedPartner?: T;
  legalName?: T;
  nipt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  parent?: T;
  center?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  category?: T;
  relatedAreas?: T;
  relatedCompanies?: T;
  relatedProjects?: T;
  author?: T;
  publishedAt?: T;
  contentType?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-requests_select".
 */
export interface ListingRequestsSelect<T extends boolean = true> {
  requestStatus?: T;
  ownerName?: T;
  ownerPhone?: T;
  ownerEmail?: T;
  city?: T;
  areaName?: T;
  address?: T;
  listingType?: T;
  propertyType?: T;
  rooms?: T;
  areaSqm?: T;
  floor?: T;
  askingPrice?: T;
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  hasDocumentation?: T;
  termsVersion?: T;
  termsAcceptedAt?: T;
  submittedLocale?: T;
  ipHash?: T;
  assignedAgent?: T;
  internalNotes?: T;
  rejectionReason?: T;
  linkedProperty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  sourceType?: T;
  sourceId?: T;
  sourceTitle?: T;
  locale?: T;
  handled?: T;
  assignedAgent?: T;
  termsVersion?: T;
  termsAcceptedAt?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  photo?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}